services:
  auth-postgres:
    image: postgres:17
    container_name: auth-postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-auth_multi_tenants}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data:
