spring.application.name=hunger
server.port=8081

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:hunger}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Jwt
security.jwt.issuer=hunger
security.jwt.audience=hunger-api
security.jwt.access-token-ttl=10m

security.jwt.private-key-location=${JWT_PRIVATE_KEY_LOCATION:file:.local/keys/access-token-private.pem}
security.jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION:file:.local/keys/access-token-public.pem}
